name: hive_flutter
description: A new Flutter project for Hive restaurant and job seeker application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0' # Updated to a stable version range for Flutter 3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7
  google_maps_flutter: ^2.5.3
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.4
  fluttertoast: ^8.0.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Add any assets your app needs here:
  #assets:
  # - images/logo.png
  # - assets/config.json

  # Uncomment and add any fonts your app needs here:
  # fonts:
  #   - family: Open Sans
  #     fonts:
  #       - asset: fonts/OpenSans-Regular.ttf
  #       - asset: fonts/OpenSans-Italic.ttf
  #         style: italic
  #       - asset: fonts/OpenSans-Bold.ttf
  #         weight: 700
