name: hive_flutter
description: A new Flutter project for Hive restaurant and job seeker application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase - Updated to latest compatible versions
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7
  firebase_storage: ^11.6.0

  # Maps - Updated to compatible versions
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.8
  # REMOVED: flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5

  # UI Components
  cupertino_icons: ^1.0.6
  badges: ^3.1.2

  # Utilities
  url_launcher: ^6.2.4
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  file_picker: ^10.1.9

  # Map components - Updated to latest compatible versions
  flutter_map: ^6.1.0
  flutter_map_marker_cluster: ^1.3.4
  latlong2: 0.9.1

  # HTTP - Updated
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# Dependency overrides to resolve conflicts
dependency_overrides:
  # Override for map compatibility
  http: ^1.1.2
  web: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/profileimage.png