name: hive_flutter
description: A new Flutter project for Hive restaurant and job seeker application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.8
  google_api_headers: ^1.6.0
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.4
  fluttertoast: ^8.0.8
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  badges: ^2.0.2
  firebase_storage: ^11.0.6
  file_picker: ^5.2.3
  flutter_map: ^4.0.0  # Downgrade to a version compatible with http ^0.13.1
  latlong2: ^0.8.1
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/profileimage.png
