// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcFQ1AW9rx407WnP2ES0IIJzZCz8JI7B0',
    appId: '1:260182988802:web:2d3cd6a2499ea8c0dcef1b',
    messagingSenderId: '260182988802',
    projectId: 'vesta-5e1d2',
    authDomain: 'vesta-5e1d2.firebaseapp.com',
    storageBucket: 'vesta-5e1d2.appspot.com',
    measurementId: 'G-37TBF188SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6q0xYkFMXomhYwp5SI4iAZDRsLXVnTrE',
    appId: '1:260182988802:android:4612fd57e0ba30f0dcef1b',
    messagingSenderId: '260182988802',
    projectId: 'vesta-5e1d2',
    storageBucket: 'vesta-5e1d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOcXNnUhpBVji5sqDXW2_ffqRn_asb0ZE',
    appId: '1:260182988802:ios:8fb5d8f8c91d110cdcef1b',
    messagingSenderId: '260182988802',
    projectId: 'vesta-5e1d2',
    storageBucket: 'vesta-5e1d2.appspot.com',
    androidClientId: '260182988802-2veic2sd5aoirsvscg4tjr3pgrnj2bee.apps.googleusercontent.com',
    iosClientId: '260182988802-7t3360krsci1aee0td4dm9buns4i7m2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiveFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOcXNnUhpBVji5sqDXW2_ffqRn_asb0ZE',
    appId: '1:260182988802:ios:a85ce2946fde0232dcef1b',
    messagingSenderId: '260182988802',
    projectId: 'vesta-5e1d2',
    storageBucket: 'vesta-5e1d2.appspot.com',
    androidClientId: '260182988802-2veic2sd5aoirsvscg4tjr3pgrnj2bee.apps.googleusercontent.com',
    iosClientId: '260182988802-8g863eom5dpv87u1r8vc4sug0g4ruuta.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiveFlutter.RunnerTests',
  );
}
